#+TITLE: Emacs configuration

#+STARTUP: overview

* Introduction

This =Readme.org= file is the entry point to my Emacs configuration. It uses =org-babel= to create a literate, modular setup.

The way this works is that this =org-mode= file contains both descriptive text explaining each part of the configuration, and source code blocks that define the actual behavior. When processed by =org-babel=, the code blocks are "tangled" into a =Readme.el= file, which is then loaded by Emacs on startup.

In other words: every piece of Emacs Lisp in this file *is* the real configuration I use. Neat, right?

* Initial configuration (must be at the beginning)

** Start the Emacs server

We start the server in order to be able to use =emacsclient=.

#+begin_src emacs-lisp
  (require 'server)
  (unless (server-running-p)
    (server-start))
#+end_src

** Set up and initialize package manager

#+begin_src emacs-lisp
  (require 'package)
  (setq package-user-dir (expand-file-name "elpa/" user-emacs-directory))

  (setq package-archives '(("gnu"       . "http://elpa.gnu.org/packages/")
                           ("melpa"     . "https://melpa.org/packages/")
                           ))

  (setq package-enable-at-startup nil)
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+end_src

** Set up =use-package=

#+begin_src emacs-lisp
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

* Interface tweaks

Small interface tweaks to simplify the look and feel

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (fset 'yes-or-no-p 'y-or-n-p)
  (blink-cursor-mode 0)
  (show-paren-mode)
  (setq ring-bell-function 'ignore)
#+end_src

* Appearance

** Font

Set default font

*** Jetbrains Mono

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :family "JetBrains Mono" :height 150)
  (add-to-list 'default-frame-alist '(font . "JetBrains Mono 15"))
#+end_src

** Theme

*** ir-black

#+begin_src emacs-lisp
  (use-package ir-black-theme
    :ensure t
    :config
    (load-theme 'ir-black t))
#+end_src

*** Disable other themes

#+begin_src emacs-lisp
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme 'ir-black t)
#+end_src

** Indentation Guides

Highlight the indentation level of programming files

#+begin_src emacs-lisp
  (use-package indent-guide
    :ensure t
    :hook ((prog-mode yaml-mode) . indent-guide-mode)
    :custom
    (indent-guide-char "│")
    (indent-guide-delay 0.1)
    (indent-guide-recursive t))
#+end_src

* Configurations

** Buffer

Auto revert buffers

#+begin_src emacs-lisp
  (global-auto-revert-mode 1)
#+end_src

Reload file with =<f5>=

#+begin_src emacs-lisp
  (global-set-key (kbd "<f5>") 'revert-buffer)
#+end_src

** Word and line wrap

Don't allow lines to overflow the screen

#+begin_src emacs-lisp
  (setq-default truncate-lines nil)
  (setq-default word-wrap t)
#+end_src

* Global keybindings

** Define keybindings on the fly

Use =H-k= to define keybindings on the fly

#+begin_src emacs-lisp
  (global-set-key (kbd "H-k") 'global-set-key)
#+end_src

** Finding files

Find files in the current project

#+begin_src emacs-lisp
  (global-set-key (kbd "H-f") 'project-find-file)
#+end_src

* Window movement

** Winner mode

Navigate window configuration history

#+begin_src emacs-lisp
  (winner-mode 1)
#+end_src

** Global keybindings

#+begin_src emacs-lisp
  (global-set-key (kbd "H-<left>")  'windmove-left)
  (global-set-key (kbd "H-<right>") 'windmove-right)
  (global-set-key (kbd "H-<up>")    'windmove-up)
  (global-set-key (kbd "H-<down>")  'windmove-down)

  (global-set-key (kbd "H-w") 'balance-windows)
#+end_src

* Dired

This line enables =dired-find-alternate-file=, which allows you to open a file from dired using the =a= keybinding without being promped.

#+begin_src emacs-lisp
  (put 'dired-find-alternate-file 'disabled nil)
#+end_src

* Try

Try packages on the fly without the need to install them.

Once emacs is restarted, the package goes away.

#+begin_src emacs-lisp
  (use-package try :ensure t)
#+end_src

* Which key

Discover available keybindings.

#+begin_src emacs-lisp
  (which-key-setup-side-window-bottom)

  (require 'which-key)
  (which-key-mode)
#+end_src

* Completion UI

** Vertico

Vertico provides a vertical completion UI using Emacs' built-in completion system.
It improves `completing-read` without introducing external frameworks.

#+begin_src emacs-lisp
  (use-package vertico
    :init
    (vertico-mode 1))
#+end_src

** Orderless

Orderless improves the way Emacs matches completion candidates. Instead of matching strictly from the beginning, it lets you type space-separated components in any order.

#+begin_src emacs-lisp
  (use-package orderless
    :init
    (setq completion-styles '(orderless)
          completion-category-defaults nil))
#+end_src

** Consult

Consult provides a set of powerful search and navigation commands, enhancing the built-in Emacs UX.

#+begin_src emacs-lisp
  (use-package consult
    :bind
    (("C-s" . consult-line)                  ;; search in current buffer
     ("C-x b" . consult-buffer)              ;; switch buffer
     ("C-x 4 b" . consult-buffer-other-window)
     ("M-y" . consult-yank-pop)              ;; show kill ring
     ("C-c f" . consult-find)                ;; find files recursively
     ;; ("C-c g" . consult-git-grep)            ;; search in git project
     ("C-c r" . consult-ripgrep)             ;; ripgrep (needs to be installed)
     ("C-c m" . consult-imenu)))             ;; jump to symbol in buffer
#+end_src

** Marginalia

Marginalia adds annotations to minibuffer completion candidates, making them easier to understand and choose.

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src
